version: '3'
services:
  auth_app:
    hostname: auth_app
    image: golang:1.14-alpine
    command: go run cmd/main.go
    working_dir: '/go/src/github.com/YumaUeno123/auth_go'
    volumes:
    - ../:/go/src/github.com/YumaUeno123/auth_go
    - ${AUTH_GO_PATH}/pkg:/go/pkg
    ports:
    - 8081:8081
  mysql:
    hostname: mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: auth_go
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
    - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3306:3306